# Generated by Django 2.2.6 on 2019-11-10 00:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('date', models.DateField()),
                ('local', models.CharField(default='', max_length=30)),
                ('content', models.CharField(default='', max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(default='', max_length=16)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('update_by', models.CharField(default='', max_length=16)),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'event_day',
            },
        ),
        migrations.CreateModel(
            name='MyUUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('password', models.CharField(default='', max_length=32)),
                ('mail', models.CharField(default='', max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(default='', max_length=16)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('update_by', models.CharField(default='', max_length=16)),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
