# Generated by Django 2.2.7 on 2019-12-13 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventday',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='event_management.User'),
            preserve_default=False,
        ),
    ]
