# Generated by Django 2.2.7 on 2020-02-26 05:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.CharField(default='0', max_length=1)),
                ('created_user', models.SlugField(default=None)),
                ('updated_user', models.SlugField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=20)),
                ('url', models.CharField(default='', max_length=20)),
                ('level', models.CharField(default='', max_length=20)),
                ('order', models.CharField(default='', max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event_management.Menu')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
