# Generated by Django 2.2.7 on 2020-03-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_menu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(default='', max_length=50),
        ),
    ]
